### ISSUE TITLE
nba_data and e2e_data not found in text_content_manipulation

### ISSUE THREAD

**Issue by catch22out** [ha-lins/DTG-SI#1]
When  i want to input 
git clone https://github.com/ZhitingHu/text_content_manipulation
cd text_content_manipulation/
mv nba_data/ ../nba_data
mv e2e_data/ ../e2e_data
then I cd text_content_manipulation/
but there is no nba_data ,,so if the dataset changed?

**Comment by ha-lins** [comment]
Hi @catch22out,

Thanks for your question. The dataset is in this [repo](https://github.com/ha-lins/DTG-SI-data). I've updated the README.

**Comment by catch22out** [comment]
tk you for updating~
