### ISSUE TITLE
There is something wrong with the texar you provide

### ISSUE THREAD

**Issue by catch22out** [ha-lins/DTG-SI#2]
The texar-unrelease you provide is 0.1.0 not 0.2.0.  I am not sure whether texar 0.1.0 could run without error.

**Comment by ha-lins** [comment]
Hi @catch22out,

Pls install the texar from the [google drive](https://drive.google.com/file/d/1wqzhyaoxapVPfXotZhulBjlvMXSDKhd0/view). Other people have ran the code successfully. My environmental config is [here](https://github.com/ha-lins/DTG-SI/blob/master/environment.yaml).

Btw, could you provide more error information? Thanks!
